[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libxss1",
  "libasound2",
  "fonts-liberation"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pip install playwright"
]

[start]
cmd = "python main.py"
