[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libxss1",
  "libasound2t64",
  "fonts-liberation"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install playwright",
  "playwright install chromium",
  "playwright install-deps chromium"
]

[start]
cmd = "python main.py"
