[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "cups", "libdrm", "dbus", "libxkbcommon", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "mesa", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "python scraper.py"
