[phases.setup]
aptPkgs = [
  "python3",
  "python3-pip",
  "chromium",
  "chromium-driver",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libxss1",
  "libasound2t64",
  "fonts-liberation"
]

[phases.install]
cmds = ["python3 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3 main.py"
